### PR TITLE
Use the correct preprocess hook for paragraph item

### LINKED ISSUE #110: Use the correct preprocess function to add the modal administration
This relates to #91 - specifically see my comment https://github.com/backdrop-contrib/paragraphs/issues/91#issuecomment-986095491

Preprocessing of Entity Plus entities is confusing. One would logically assume that the following preprocess hook would work: `template_preprocess_paragraphs_item()` to preprocess paragraph items. But no. These preprocessing functions never get called. Which is what led people to use #theme_wrappers (to force that hook to run, but caused other issues). This also led a previous PR to use `paragraphs_preprocess()` to add the modal classes. Instead, you must use hook_preprocess_entity_plus and use if statements to check that you are preprocessing the right template/entity. 

I will submit a PR in a minute.

IMPORTANT. For the PR to work you must:

- Remove this line:  [here](https://github.com/backdrop-contrib/paragraphs/blob/769e1db92419cfee145a80ee1e573c0f5a14cd00/paragraphs.field_formatter.inc#L128)..
- Apply the modification to the template to use array_classes done in Use $classes_array instead of $classes to apply css classes #109

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes #110

In order for the fix to work you MUST also apply #109

### CODE REVIEW

**Comment by laryn** [comment]
Thank you @argiepiano -- much appreciated all the digging on this one. I'll just have to make a prominent warning about the other hook no longer working at all when I release this. Your work does make sense!

**Comment by argiepiano** [comment]
> I'll just have to make a prominent warning about the other hook no longer working at all when I release this. Your work does make sense!

Eventually we may want to take a look at how Entity Plus handles the theming of custom entities such as Paragraphs. 

Another option while we look into how entity plus handles entity viewing, would have been to implement hook_entity_plus_view and change the theme right there. I believe that would have allowed us to use the paragraph_item preprocess function.

**Comment by argiepiano** [comment]
Yet a third way to avoid using hook_preprocess_entity_plus and use preprocess_paragraphs_item would have been for Paragraphs to extend class `EntityPlusController` to implement buildContent, and specify the theme to be used to display Paragraphs. I noticed that Paragraphs doesn't extend `EntityPlusController` at all, and therefore relies on its method to build content and theme the paragraph entity

**Comment by laryn** [comment]
@argiepiano Ah, interesting. That third way sounds like a good option actually -- that would allow things to function the way many people assume they should, right?

**Comment by argiepiano** [comment]
> @argiepiano Ah, interesting. That third way sounds like a good option actually -- that would allow things to function the way many people assume they should, right?

Right. I can take a stab at that later today and test. It shouldn't be too involved

**Comment by laryn** [comment]
That sounds great. I was about to start reworking Classy Paragraphs (since it uses `hook_preprocess_paragraphs_item` but if this is achievable in the short term I'll pause on that. (Would be nice not to have to tell everyone to rewrite custom functions they may be using on the next update, too).

**Comment by argiepiano** [comment]
@laryn I did not have a chance to try this last night, but I'll try tonight. Got entangled with Entity Plus, cleaning up the taxonomy term and vocabulary wrappers!

**Comment by laryn** [comment]
@argiepiano Sounds tangly!

**Pull request merged**
