### PR TITLE
Issue #120. Add typehinting to buildContent

### LINKED ISSUE #120: Fix typehinting of buildContent in ParagraphsItemEntityController
EntityControllerInterface::buildContent() now typehints its first argument, $entity,  as `EntityInterface`. All classes that implement this interface or an extension of this interface (including ParagraphsItemEntityController) must typehint the first argument the same way.

This is not an issue with PHP 7.3 or 7.4, but it does throw a fatal error in 7.1 ,  and probably also in 7.0. See this report in Entity Plus issue queue. https://github.com/backdrop-contrib/entity_plus/issues/117

I'll submit a PR for this.

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes #120

### CODE REVIEW

**Comment by argiepiano** [comment]
The functional test failed because  PR https://github.com/backdrop-contrib/entity_plus/pull/118 has not yet been merged in Entity Plus

**Comment by argiepiano** [comment]
Close and reopen to check test after merging the Entity Plus PR

**Comment by argiepiano** [comment]
Close and reopen to check test after merging the Entity Plus PR

**Comment by laryn** [comment]
Thanks @argiepiano !

**Pull request merged**
