### PR TITLE
Issue #62: organize buttons into a dropdown

### LINKED ISSUE #62: Move Paragraphs item action buttons to top right in a drop-down style.
This issue is solely for moving the actions on a Paragraphs item into the top right in a drop-down button style (though not necessarily a literal dropdown button). The D7 issue this started from is below, but any additional aspects desired from that D7 issue would need separate issues filed.

--------
This is an issue from the Drupal 7 queue that is marked "Needs Review" and could improve the UI.

> ## Problem/Motivation
>
> Basic support for collapsible paragraph items was added in #2273555: Collapsible paragraphs in node edit form, but a number of UX enhancements requested in that issue failed to make it into the committed patches and the UI could still use some refinement. To avoid confusion, I'm copying those outstanding issues here for continued development.
>
> ## Proposed resolution
>
> 1.    Move all the actions available on a paragraph item (edit/collapse/remove) into a single drop button, instead of displaying them as separate buttons. This drop button can be floated right at the top of the paragraph item, saving significant space. *This ticket*
> 1.    Add links at the top of the paragraphs field to expand all/collapse all. https://github.com/backdrop-contrib/paragraphs/issues/177
> 1.    Add an option to the drop button for each paragraph item to reset any unsaved changes. https://github.com/backdrop-contrib/paragraphs/issues/185
> 1.    Add an option to completely disable collapsing items in the configuration form for paragraphs fields.

https://www.drupal.org/project/paragraphs/issues/2476253

### PR DESCRIPTION
**Pull request by herbdool**
Fixes #62.

Alternative that puts buttons other than "Edit" into a dropdown. The dropdown is custom since there's nothing in core to help with dropdowns that contain buttons.

### CODE REVIEW

**Comment by herbdool** [comment]
@irinaz have you had a chance to test this? Would be good to have a go at this so it's easier for @laryn to review.

**Comment by irinaz** [comment]
@herbdool @laryn look great to me.  I tested it with https://github.com/backdrop-contrib/paragraphs_aplenty and I think that this change can be merged as is.

**Comment by irinaz** [comment]
@herbdool , there was small styling difference for unpublish/remove links for cards/card , but I think that new display is much better even with this glitch. 

Screenshot 2024-06-14 at 2 05 41 PM

Screenshot 2024-06-14 at 2 07 30 PM

Thank you so much for making it work!!

**Comment by herbdool** [comment]
@irinaz for testing.

I can't recreate that issue you've got with the dropdown. This is what I see:

Screenshot from 2024-06-15 10-36-22

Did you test on a fresh install? It's best to do it clean to ensure there's not something else interfering.

**Comment by irinaz** [comment]
@herbdool , I tested on another site and I see what you see.  
@laryn , I think that this is ready for merge :)

**Comment by laryn** [comment]
@herbdool Can you check/test this commit and let me know what you think?
https://github.com/backdrop-contrib/paragraphs/pull/180/commits/92c48062082c8f70df60c575fdfa3ce2c04c5d9c

**Comment by herbdool** [comment]
I'll check it soon.

**Comment by herbdool** [comment]
@laryn this works well for me. Thanks for fixing the JS! I suggested a couple tweaks to file location, etc. but I think it's more or less ready.

**Pull request merged**
